frasesTarde = [
    "La tarde es el momento perfecto para recargar energías y seguir adelante con tus metas.",
    "No importa cómo empezó tu día, lo importante es cómo decides terminarlo. ¡Sigue adelante!",
    "Las tardes son una oportunidad para reflexionar y planificar un futuro exitoso.",
    "Cada tarde es una página en blanco para escribir nuevas historias de éxito.",
    "No dejes que el cansancio de la mañana te detenga. La tarde es el momento de brillar.",
    "La tarde es un buen momento para recordar que cada esfuerzo vale la pena.",
    "No te rindas, lo mejor del día aún está por venir.",
    "Aprovecha la tarde para hacer algo que acerque más a tus sueños.",
    "La tarde es el momento perfecto para un nuevo comienzo.",
    "Cree en ti mismo y sigue adelante, sin importar las dificultades que enfrentes.",
    "Cada tarde es una nueva oportunidad para alcanzar tus metas.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. ¡Sigue adelante!",
    "No importa lo lento que avances, lo importante es no detenerse.",
    "Las grandes cosas nunca vienen de zonas de confort. Atrévete a soñar en grande.",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.",
    "La tarde es el momento de recordar que cada día es una nueva oportunidad para ser mejor.",
    "Nunca es tarde para ser lo que podrías haber sido.",
    "La clave del éxito es empezar antes de estar listo.",
    "No esperes a que las condiciones sean perfectas para empezar. Empezar hace que las condiciones sean perfectas.",
    "Cada tarde es una nueva oportunidad para aprender algo nuevo y crecer.",
    "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor para continuar.",
    "No sueñes con el éxito, trabaja para lograrlo.",
    "La tarde es un buen momento para recordar que las grandes cosas llevan tiempo.",
    "Nunca es demasiado tarde para establecer un nuevo objetivo o soñar un nuevo sueño.",
    "El camino al éxito está lleno de fracasos, pero cada uno es una lección que te acerca más a tus metas.",
    "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes al no intentarlo.",
    "Cada tarde es una oportunidad para acercarte más a tus sueños.",
    "La perseverancia no es una carrera larga; son muchas carreras cortas, una tras otra.",
    "El éxito no llega de la noche a la mañana. Llega a través de trabajo duro y dedicación constante.",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.",
    "La tarde es un buen momento para recordar que cada pequeño paso cuenta.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "No importa cuántas veces caigas, lo importante es cuántas veces te levantes.",
    "No dejes que los fracasos del pasado arruinen el éxito del futuro.",
    "Cada tarde es una oportunidad para hacer algo que nunca has hecho antes.",
    "No te compares con los demás. Compárate con la persona que eras ayer.",
    "La tarde es el momento perfecto para recordar que cada día es una nueva oportunidad.",
    "No hay atajos para ningún lugar al que valga la pena ir.",
    "El éxito es la suma de pequeños esfuerzos, repetidos día tras día.",
    "No te rindas, el principio es siempre la parte más difícil."
]
