frasesNoche = [
    "La noche es el momento perfecto para reflexionar sobre tus logros y planificar tus sueños.",
    "Cada noche es una oportunidad para descansar, recargar energías y prepararte para un nuevo día.",
    "Deja que la paz de la noche te inspire a seguir adelante con tus sueños mañana.",
    "No importa cuán difícil haya sido el día, cada noche es una nueva oportunidad para comenzar de nuevo.",
    "La noche es un buen momento para soltar las preocupaciones y enfocarte en lo que quieres lograr.",
    "Cada día trae consigo nuevos retos y oportunidades. Descansa esta noche para enfrentarlos con fuerza mañana.",
    "Antes de dormir, recuerda que los sueños están al alcance de tu mano.",
    "La noche es el lienzo donde pintas tus sueños y deseos. Asegúrate de soñar en grande.",
    "Las estrellas brillan más en la oscuridad. Tus sueños también pueden brillar si trabajas en ellos con pasión.",
    "Cada noche es un paso más cerca de alcanzar tus metas. Descansa bien para conquistar el mañana.",
    "Los logros de hoy son los sueños que se hicieron realidad. Celebra tus éxitos esta noche.",
    "La noche es el momento perfecto para dejar ir lo que no puedes controlar y enfocarte en lo que puedes cambiar.",
    "Permítete relajarte y agradecer todo lo bueno que has logrado hoy.",
    "La tranquilidad de la noche es el mejor momento para planificar un futuro brillante.",
    "Descansa esta noche sabiendo que cada día es una oportunidad para acercarte a tus sueños.",
    "La noche es una pausa para prepararte para el éxito de mañana. Aprovecha para descansar y recargar energías.",
    "La serenidad de la noche es el mejor momento para recordar tus fortalezas y prepararte para nuevos desafíos.",
    "Antes de dormir, piensa en todo lo positivo que has logrado hoy y en lo que te espera mañana.",
    "Cada noche es una nueva oportunidad para dejar atrás lo viejo y abrazar lo nuevo.",
    "La paz de la noche te da la fuerza para enfrentar los desafíos del día siguiente.",
    "La noche es el mejor momento para soñar en grande y visualizar tu éxito futuro.",
    "Deja que la calma de la noche te inspire a seguir persiguiendo tus metas con determinación.",
    "Antes de dormir, asegúrate de estar en paz contigo mismo y con tus logros.",
    "La noche es el momento ideal para relajarte y planificar tus próximos pasos con claridad.",
    "Descansa tranquilo sabiendo que cada día es una nueva oportunidad para avanzar hacia tus sueños.",
    "La noche es el final de un capítulo, y mañana es el comienzo de una nueva aventura.",
    "Permítete soñar en grande esta noche y despierta con la determinación de hacer realidad esos sueños.",
    "La noche es un momento para reflexionar sobre lo que has logrado y preparar el terreno para un futuro aún mejor.",
    "Relájate y disfruta de la noche, mañana es un nuevo día lleno de posibilidades.",
    "La calma de la noche es el mejor momento para reconocer tu esfuerzo y prepararte para nuevos retos.",
    "Cada noche es una invitación a descansar, reflexionar y despertar con renovada energía.",
    "La tranquilidad nocturna te da la oportunidad de centrarte en tus objetivos y recargar tus fuerzas.",
    "Deja que la noche te brinde la paz que necesitas para comenzar el próximo día con un espíritu renovado.",
    "La noche es el final perfecto para un día lleno de logros y el comienzo de nuevas oportunidades.",
    "Antes de cerrar los ojos, recuerda que cada día es una nueva oportunidad para avanzar hacia tus sueños.",
    "Descansa y confía en que mañana será otro día lleno de oportunidades para brillar.",
    "La noche te ofrece un respiro para prepararte mentalmente para el éxito que te espera mañana."
]
