frasesNoche = [
    "La noche es el momento perfecto para reflexionar sobre tus logros y planificar tus sueños. Te amo.",
    "Cada noche es una oportunidad para descansar, recargar energías y prepararte para un nuevo día. Descansa, amor mío.",
    "Deja que la paz de la noche te inspire a seguir adelante con tus sueños mañana. Siempre estaré a tu lado.",
    "No importa cuán difícil haya sido el día, cada noche es una nueva oportunidad para comenzar de nuevo. Buenas noches, mi vida.",
    "La noche es un buen momento para soltar las preocupaciones y enfocarte en lo que quieres lograr. Te admiro mucho.",
    "Cada día trae consigo nuevos retos y oportunidades. Descansa esta noche para enfrentarlos con fuerza mañana. Estoy contigo.",
    "Antes de dormir, recuerda que los sueños están al alcance de tu mano. Te apoyo en cada uno de ellos.",
    "La noche es el lienzo donde pintas tus sueños y deseos. Asegúrate de soñar en grande. Siempre creeré en ti.",
    "Las estrellas brillan más en la oscuridad. Tus sueños también pueden brillar si trabajas en ellos con pasión. Dulces sueños, mi estrella.",
    "Cada noche es un paso más cerca de alcanzar tus metas. Descansa bien para conquistar el mañana. Estoy orgulloso de ti.",
    "Los logros de hoy son los sueños que se hicieron realidad. Celebra tus éxitos esta noche. Buenas noches, amor.",
    "La noche es el momento perfecto para dejar ir lo que no puedes controlar y enfocarte en lo que puedes cambiar. Siempre estaré aquí para ti.",
    "Permítete relajarte y agradecer todo lo bueno que has logrado hoy. Eres increíble.",
    "La tranquilidad de la noche es el mejor momento para planificar un futuro brillante. Te amo y confío en ti.",
    "Descansa esta noche sabiendo que cada día es una oportunidad para acercarte a tus sueños. Estoy aquí para apoyarte.",
    "La noche es una pausa para prepararte para el éxito de mañana. Aprovecha para descansar y recargar energías. Buenas noches, cariño.",
    "La serenidad de la noche es el mejor momento para recordar tus fortalezas y prepararte para nuevos desafíos. Te admiro más de lo que puedes imaginar.",
    "Antes de dormir, piensa en todo lo positivo que has logrado hoy y en lo que te espera mañana. Estoy contigo en cada paso.",
    "Cada noche es una nueva oportunidad para dejar atrás lo viejo y abrazar lo nuevo. Juntos podemos con todo.",
    "La paz de la noche te da la fuerza para enfrentar los desafíos del día siguiente. Descansa, mi amor.",
    "La noche es el mejor momento para soñar en grande y visualizar tu éxito futuro. Siempre creeré en ti.",
    "Deja que la calma de la noche te inspire a seguir persiguiendo tus metas con determinación. Buenas noches, corazón.",
    "Antes de dormir, asegúrate de estar en paz contigo mismo y con tus logros. Eres más fuerte de lo que piensas.",
    "La noche es el momento ideal para relajarte y planificar tus próximos pasos con claridad. Descansa bien, mi amor.",
    "Descansa tranquilo sabiendo que cada día es una nueva oportunidad para avanzar hacia tus sueños. Siempre te apoyaré.",
    "La noche es el final de un capítulo, y mañana es el comienzo de una nueva aventura. Buenas noches, mi vida.",
    "Permítete soñar en grande esta noche y despierta con la determinación de hacer realidad esos sueños. Estoy aquí para ti.",
    "La noche es un momento para reflexionar sobre lo que has logrado y preparar el terreno para un futuro aún mejor. Te amo.",
    "Relájate y disfruta de la noche, mañana es un nuevo día lleno de posibilidades. Buenas noches, mi amor.",
    "La calma de la noche es el mejor momento para reconocer tu esfuerzo y prepararte para nuevos retos. Eres increíble.",
    "Cada noche es una invitación a descansar, reflexionar y despertar con renovada energía. Te amo, descansa bien.",
    "La tranquilidad nocturna te da la oportunidad de centrarte en tus objetivos y recargar tus fuerzas. Buenas noches, cariño.",
    "Deja que la noche te brinde la paz que necesitas para comenzar el próximo día con un espíritu renovado. Estoy contigo.",
    "La noche es el final perfecto para un día lleno de logros y el comienzo de nuevas oportunidades. Descansa, mi amor.",
    "Antes de cerrar los ojos, recuerda que cada día es una nueva oportunidad para avanzar hacia tus sueños. Te apoyo siempre.",
    "Descansa y confía en que mañana será otro día lleno de oportunidades para brillar. Buenas noches, mi vida.",
    "La noche te ofrece un respiro para prepararte mentalmente para el éxito que te espera mañana. Te amo y creo en ti."
]
