frasesTarde = [
    "La tarde es el momento perfecto para recargar energías y seguir adelante con tus metas. Estoy contigo en cada paso.",
    "No importa cómo empezó tu día, lo importante es cómo decides terminarlo. ¡Sigue adelante, amor!",
    "Las tardes son una oportunidad para reflexionar y planificar un futuro exitoso. Confío en ti y en tu capacidad.",
    "Cada tarde es una página en blanco para escribir nuevas historias de éxito. Juntos haremos grandes cosas.",
    "No dejes que el cansancio de la mañana te detenga. La tarde es el momento de brillar. Te admiro mucho.",
    "La tarde es un buen momento para recordar que cada esfuerzo vale la pena. Estoy orgulloso de ti.",
    "No te rindas, lo mejor del día aún está por venir. Tu perseverancia me inspira.",
    "Aprovecha la tarde para hacer algo que acerque más a tus sueños. Siempre estoy aquí para apoyarte.",
    "La tarde es el momento perfecto para un nuevo comienzo. Eres increíble en todo lo que haces.",
    "Cree en ti mismo y sigue adelante, sin importar las dificultades que enfrentes. Tienes mi apoyo incondicional.",
    "Cada tarde es una nueva oportunidad para alcanzar tus metas. Estoy aquí para animarte.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. ¡Sigue adelante, te amo!",
    "No importa lo lento que avances, lo importante es no detenerse. Estoy contigo en cada paso del camino.",
    "Las grandes cosas nunca vienen de zonas de confort. Atrévete a soñar en grande. Estoy contigo en cada sueño.",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito. Siempre creí en ti.",
    "La tarde es el momento de recordar que cada día es una nueva oportunidad para ser mejor. Estoy orgulloso de ti.",
    "Nunca es tarde para ser lo que podrías haber sido. Confío en tu potencial.",
    "La clave del éxito es empezar antes de estar listo. Eres capaz de lograrlo.",
    "No esperes a que las condiciones sean perfectas para empezar. Empezar hace que las condiciones sean perfectas. Tienes todo lo que necesitas.",
    "Cada tarde es una nueva oportunidad para aprender algo nuevo y crecer. Estoy aquí para apoyarte en cada paso.",
    "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor para continuar. Eres valiente y fuerte.",
    "No sueñes con el éxito, trabaja para lograrlo. Estoy aquí para ayudarte a alcanzar tus sueños.",
    "La tarde es un buen momento para recordar que las grandes cosas llevan tiempo. Tu esfuerzo valdrá la pena.",
    "Nunca es demasiado tarde para establecer un nuevo objetivo o soñar un nuevo sueño. Estoy aquí para animarte en cada meta.",
    "El camino al éxito está lleno de fracasos, pero cada uno es una lección que te acerca más a tus metas. Estoy contigo en cada lección.",
    "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes al no intentarlo. Siempre creeré en ti.",
    "Cada tarde es una oportunidad para acercarte más a tus sueños. Eres increíblemente capaz.",
    "La perseverancia no es una carrera larga; son muchas carreras cortas, una tras otra. Eres un verdadero ejemplo de perseverancia.",
    "El éxito no llega de la noche a la mañana. Llega a través de trabajo duro y dedicación constante. Estoy aquí para apoyarte en cada paso.",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. Estoy orgulloso de tu esfuerzo.",
    "La tarde es un buen momento para recordar que cada pequeño paso cuenta. Cada esfuerzo tuyo es valioso.",
    "El éxito es la suma de pequeños esfuerzos, repetidos día tras día. Tu dedicación me inspira.",
    "No importa cuántas veces caigas, lo importante es cuántas veces te levantes. Siempre estaré aquí para levantarte.",
    "No dejes que los fracasos del pasado arruinen el éxito del futuro. Eres fuerte y capaz de grandes cosas.",
    "Cada tarde es una oportunidad para hacer algo que nunca has hecho antes. Confío en tu habilidad para lograrlo.",
    "No te compares con los demás. Compárate con la persona que eras ayer. Eres maravillosa tal como eres.",
    "La tarde es el momento perfecto para recordar que cada día es una nueva oportunidad. Estoy aquí para apoyarte en cada nuevo comienzo.",
    "No hay atajos para ningún lugar al que valga la pena ir. Tu viaje es valioso y estoy contigo en cada paso.",
    "El éxito es la suma de pequeños esfuerzos, repetidos día tras día. Eres un verdadero ejemplo de dedicación.",
    "No te rindas, el principio es siempre la parte más difícil. Estoy aquí para animarte en cada desafío."
]
