frases = [
    "Buenos días, amor mío. Despertar contigo en mi mente hace que cada día sea perfecto.",
    "Eres el primer pensamiento en mi mente cada mañana. Te amo.",
    "Despertar sabiendo que estás en mi vida hace que cada día sea más brillante.",
    "Buenos días, mi amor. Eres mi sol y mi luna.",
    "No necesito café, solo necesito tus besos para despertar. Buenos días.",
    "Eres mi razón para sonreír cada mañana. Te amo.",
    "Buenos días, preciosa. Mi amor por ti crece con cada amanecer.",
    "Cada día es una bendición porque te tengo en mi vida. Buenos días, amor.",
    "Solo quiero empezar mi día agradeciendo al universo por haberte encontrado. Buenos días, mi vida.",
    "Despertar contigo en mi corazón hace que todo sea posible. Buenos días, mi amor.",
    "Eres mi primer pensamiento cada mañana y mi último cada noche. Buenos días, mi cielo.",
    "Buenos días, amor. Que tu día esté lleno de tantas alegrías como me das tú.",
    "No hay nada mejor que despertar sabiendo que eres mío. Buenos días, mi amor.",
    "Buenos días, mi sol. Iluminas mi vida cada día.",
    "Despertar contigo en mi mente hace que cualquier día sea maravilloso. Buenos días, amor.",
    "Eres la razón por la que sonrío cada mañana. Buenos días, preciosa.",
    "Mi amor por ti es más fuerte cada día que pasa. Buenos días, mi vida.",
    "Buenos días, amor. Eres la razón por la que mi corazón late.",
    "Despertar sabiendo que te tengo hace que cada día sea especial. Buenos días, mi amor.",
    "Buenos días, mi cielo. Eres el motivo de mi felicidad.",
    "Eres la luz que ilumina mis mañanas. Buenos días, amor.",
    "Buenos días, hermosa. Mi corazón es tuyo desde el amanecer hasta el anochecer.",
    "Despertar contigo en mis pensamientos es el mejor comienzo de mi día. Buenos días, amor.",
    "Buenos días, mi vida. No hay nada más dulce que tus besos matutinos.",
    "Eres el primer rayo de sol que toca mi alma. Buenos días, mi amor.",
    "Cada mañana me despierto más enamorado de ti. Buenos días, preciosa.",
    "Buenos días, amor. Eres el sueño del que nunca quiero despertar.",
    "Mi primer deseo cada mañana es verte sonreír. Buenos días, mi cielo.",
    "Buenos días, mi vida. Gracias por ser mi sol en los días nublados.",
    "Despertar a tu lado en mis pensamientos es mi felicidad. Buenos días, amor.",
    "Buenos días, preciosa. Mi amor por ti brilla más que el sol.",
    "Eres la melodía de mis mañanas. Buenos días, mi amor.",
    "Buenos días, mi vida. Eres el sueño más hermoso que se ha hecho realidad.",
    "No hay mejor manera de empezar el día que pensando en ti. Buenos días, amor.",
    "Buenos días, amor. Tu sonrisa es el mejor despertador.",
    "Despertar sabiendo que te tengo es mi mayor alegría. Buenos días, preciosa.",
    "Eres mi razón para levantarme cada mañana con una sonrisa. Buenos días, amor.",
    "Buenos días, mi sol. Cada día a tu lado es un regalo.",
    "Mi primer pensamiento al despertar eres tú. Buenos días, mi vida.",
    "Buenos días, amor. No hay nada más dulce que empezar el día contigo en mi mente."
]
